Adding "Vault App" (Accepted)
wwdc/2022 pull request #38
Opened 2022-05-24 19:19 UTC by geetanshatrey

2022-05-24 20:16 UTC, thisIsTheFoxe requested changes
Congrats on getting accepted! 🎉
Looks good, so far. But if there's no entry please just leave the field empty. 
Thanks.

2022-05-24 20:16 UTC, thisIsTheFoxe commented on README.md
> +|[Geetansh Atrey](https://github.com/geetanshatrey)|[GitHub](https://github.com/geetanshatrey/Vault)|-|SwiftUI, CryptoKit|Accepted|
```suggestion
|[Geetansh Atrey](https://github.com/geetanshatrey)|[GitHub](https://github.com/geetanshatrey/Vault)||SwiftUI, CryptoKit|Accepted|
```

2022-05-25 05:36 UTC, geetanshatrey commented
> Congrats on getting accepted! 🎉 Looks good, so far. But if there's no entry please just leave the field empty. Thanks.

Thanks a lot! Also, I have committed the changes you had requested.

2022-05-25 07:58 UTC, thisIsTheFoxe commented
Great, thank you :)
Please note that as we merge other entries it might cause conflicts which you can resolve right here on GitHub. Just keep in mind the alphabetical order. Sorry for the inconvenience.. 🫠

2022-05-26 14:50 UTC, geetanshatrey commented
Made the changes you had requested. Can merge now. Thanks!

2022-05-26 22:02 UTC, thisIsTheFoxe commented
Hi again,
It seems there's been some whitespace and other formatting changes now (which leads to more conflicts). Please check it again and only add your entry, keeping the rest of the file as-is.
Thanks :)

2022-05-27 11:20 UTC, geetanshatrey commented
Hey, sorry for the inconvenience. Can you review it again and check if it's fine now? Thanks!

2022-05-27 18:23 UTC, thisIsTheFoxe approved these changes
No worries looks good. 👍
Just wired that the GitHub UI shows some additions that were made already. iirc that's on purpose bc of how merging/rebasing is handled. But as long as there's no deletion it should be fine ^^

Again, congrats and thanks for your patience and fixing it.. ^-^

2022-05-27 18:23 UTC, merged